name: spypro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  audioplayers: ^5.1.0
  html_unescape: ^2.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/brain.png"

flutter:

  uses-material-design: true
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3


